import { chromium } from 'playwright';
import fs from 'fs';
import { installKvStub } from '../harness/live-kv-stub.mjs';
const SP = process.env.SP;
const seed = JSON.parse(fs.readFileSync(`${SP}/seed-kv.json`, 'utf8'));
const tsv = fs.readFileSync(`${SP}/pms-issues.tsv`, 'utf8');
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 1440, height: 1700 } });
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
p.on('console',m=>{ if(m.type()==='error') errs.push(m.text().slice(0,140)); });
await p.route(/^https?:\/\/(?!127\.0\.0\.1)/, r => /rest\/v1\/kv_store/.test(r.request().url()) ? r.continue() : r.abort());
await installKvStub(p, seed);
await p.goto('http://127.0.0.1:4180/', { waitUntil: 'domcontentloaded' }); await p.waitForTimeout(3000);
await p.locator('input[placeholder*="Ahmed"]').fill('Haris');
await p.getByRole('button', { name: 'Start' }).click(); await p.waitForTimeout(1800);
await p.getByRole('button', { name: 'Queue' }).first().click(); await p.waitForTimeout(2200);
await p.getByRole('button', { name: 'Paste the PMS queue' }).first().click(); await p.waitForTimeout(600);
await p.locator('div.fixed.inset-0 textarea').first().fill(tsv);
await p.getByRole('button', { name: 'Add to the queue' }).click(); await p.waitForTimeout(3000);
const t = await p.innerText('body');
const i = t.indexOf('Harbour Views');
console.log('FIRST THREE QUEUE ROWS AS RENDERED:\n');
console.log(t.slice(i, i + 900).split('\n').filter(Boolean).slice(0, 24).join('\n'));
console.log('\nBook buttons:', await p.getByRole('button', { name: /^Book 2026-/ }).count());
console.log('errors:', errs.length ? errs : 'none');
await p.screenshot({ path: `${SP}/LIVE-queue.png`, fullPage: true });
await b.close();
